from __future__ import annotations

import argparse
import json
import sys
import urllib.parse
from pathlib import Path
from typing import Optional, Sequence

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from story_parser.adapters import find_bwiki_detail_links
    from story_parser.extractors import HtmlTextExtractor, looks_like_html
    from story_parser.fetcher import SourceFetcher, load_url_file
    from story_parser.models import SourceRef
    from story_parser.normalize import normalize_text
    from story_parser.segment import extract_dialogue, make_document
    from story_parser.writers import (
        write_dialogue_jsonl,
        write_dialogue_markdown,
        write_parsed_markdown,
    )
else:
    from .adapters import find_bwiki_detail_links
    from .extractors import HtmlTextExtractor, looks_like_html
    from .fetcher import SourceFetcher, load_url_file
    from .models import SourceRef
    from .normalize import normalize_text
    from .segment import extract_dialogue, make_document
    from .writers import write_dialogue_jsonl, write_dialogue_markdown, write_parsed_markdown


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "sources" / "parsed_story.md"
DEFAULT_CACHE = ROOT / "sources" / ".story-cache"


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fetch/parse complex story pages and extract character dialogue."
    )
    parser.add_argument("--url", action="append", default=[], help="Story page URL. Repeatable.")
    parser.add_argument("--urls-file", type=Path, help="File containing one URL per line.")
    parser.add_argument("--html", action="append", type=Path, default=[], help="Saved HTML file. Repeatable.")
    parser.add_argument("--text", action="append", type=Path, default=[], help="Copied text/markdown file. Repeatable.")
    parser.add_argument("--mirror-manifest", type=Path, help="Parse HTML files listed in a mirror manifest generated by mirror_story_pages.py.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help=f"Cleaned story Markdown output. Default: {DEFAULT_OUTPUT}")
    parser.add_argument("--dialogue-output", type=Path, help="Optional dialogue-only Markdown output.")
    parser.add_argument("--jsonl-output", type=Path, help="Optional dialogue-only JSONL output.")
    parser.add_argument("--character", action="append", default=[], help="Speaker to extract. Repeatable. Omit to extract all dialogue.")
    parser.add_argument("--follow-detail-links", action="store_true", help="For BWiki overview pages, also parse linked detailed dialogue pages.")
    parser.add_argument("--max-pages", type=int, default=0, help="Maximum total pages to parse when following links. 0 means no limit.")
    parser.add_argument("--cache-dir", type=Path, default=DEFAULT_CACHE, help="URL HTML cache directory.")
    parser.add_argument("--no-cache", action="store_true", help="Disable URL cache.")
    parser.add_argument("--timeout", type=int, default=30, help="HTTP timeout seconds.")
    parser.add_argument("--retries", type=int, default=3, help="HTTP retry count.")
    parser.add_argument("--retry-sleep", type=float, default=1.5, help="Seconds between retries.")
    parser.add_argument("--append", action="store_true", help="Append instead of replacing outputs.")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    inputs = collect_inputs(args)
    if not inputs:
        print("No input. Use --url, --urls-file, --html, or --text.", file=sys.stderr)
        return 2

    fetcher = SourceFetcher(
        cache_dir=None if args.no_cache else args.cache_dir,
        timeout=args.timeout,
        retries=args.retries,
        retry_sleep=args.retry_sleep,
    )
    extractor = HtmlTextExtractor()

    documents = []
    seen_values: set[str] = set()
    index = 0
    while index < len(inputs):
        if args.max_pages and len(documents) >= args.max_pages:
            break

        item = inputs[index]
        index += 1
        if item["value"] in seen_values:
            continue
        seen_values.add(item["value"])

        print(f"[{len(documents) + 1}/{len(inputs)}] parsing {item['value']}", file=sys.stderr)
        raw = fetcher.read_source(item["value"])

        if args.follow_detail_links and item["kind"] == "url":
            detail_links = find_bwiki_detail_links(raw, item["value"])
            for link in detail_links:
                if link not in seen_values and not any(existing["value"] == link for existing in inputs):
                    inputs.append({"kind": "url", "value": link})

        should_extract_html = item["kind"] in {"url", "html"} or looks_like_html(raw)
        text = extractor.extract(raw) if should_extract_html else raw
        lines = normalize_text(text)
        source = SourceRef(
            value=item["value"],
            kind=item["kind"],
            title=source_title(item["value"], index),
        )
        documents.append(make_document(source, lines))

    write_parsed_markdown(args.output, documents, append=args.append)
    print(f"Wrote {args.output}", file=sys.stderr)

    records = []
    if args.dialogue_output or args.jsonl_output:
        for document in documents:
            records.extend(extract_dialogue(document, speakers=args.character))

    if args.dialogue_output:
        write_dialogue_markdown(args.dialogue_output, records, append=args.append)
        print(f"Wrote {args.dialogue_output}", file=sys.stderr)

    if args.jsonl_output:
        write_dialogue_jsonl(args.jsonl_output, records, append=args.append)
        print(f"Wrote {args.jsonl_output}", file=sys.stderr)

    return 0


def collect_inputs(args: argparse.Namespace) -> list[dict[str, str]]:
    inputs: list[dict[str, str]] = []
    urls = list(args.url)
    if args.urls_file:
        urls.extend(load_url_file(args.urls_file))

    for url in urls:
        inputs.append({"kind": "url", "value": url})
    for path in args.html:
        inputs.append({"kind": "html", "value": str(path)})
    for path in args.text:
        inputs.append({"kind": "text", "value": str(path)})
    if args.mirror_manifest:
        inputs.extend(collect_manifest_inputs(args.mirror_manifest))

    return inputs


def collect_manifest_inputs(manifest_path: Path) -> list[dict[str, str]]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    output_dir = manifest_output_dir(manifest, manifest_path)
    inputs: list[dict[str, str]] = []
    for page in manifest.get("pages", []):
        local_path = page.get("local_path")
        if not local_path:
            continue
        path = output_dir / local_path
        inputs.append({"kind": "html", "value": str(path)})
    return inputs


def source_title(value: str, index: int) -> str:
    if value.startswith("http://") or value.startswith("https://"):
        parsed = urllib.parse.urlparse(value)
        leaf = Path(urllib.parse.unquote(parsed.path)).name or parsed.netloc
    else:
        leaf = Path(value).name
    return f"{index:02d} {leaf}"


def manifest_output_dir(manifest: dict, manifest_path: Path) -> Path:
    value = manifest.get("output_dir")
    if not value:
        return manifest_path.parent
    path = Path(value)
    return path if path.is_absolute() else ROOT / path


if __name__ == "__main__":
    raise SystemExit(main())
