from __future__ import annotations

import datetime as dt
import json
from pathlib import Path
from typing import Iterable, Sequence

from .models import DialogueRecord, ParsedDocument, ParsedLine
from .normalize import lines_to_text


def write_parsed_markdown(path: Path, documents: Sequence[ParsedDocument], append: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with path.open(mode, encoding="utf-8", newline="\n") as handle:
        if append:
            handle.write("\n")
        handle.write("# Parsed Story Sources\n\n")
        handle.write("> Generated by scripts/story_parser. Review before using as evidence.\n\n")
        for document in documents:
            handle.write(f"## {document.source.title}\n\n")
            handle.write(f"- Source: {document.source.value}\n")
            handle.write(f"- Source type: {document.source.kind}\n")
            handle.write(f"- Parsed: {now_iso()}\n")
            handle.write(f"- Sections: {len(document.sections)}\n\n")
            handle.write(lines_to_text(document.lines))
            handle.write("\n")


def write_dialogue_markdown(path: Path, records: Sequence[DialogueRecord], append: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with path.open(mode, encoding="utf-8", newline="\n") as handle:
        if append:
            handle.write("\n")
        handle.write("# Dialogue Extract\n\n")
        handle.write("> Generated by scripts/story_parser. Branch choices may need manual review.\n\n")

        current_source = None
        current_section = None
        for record in records:
            if record.source.value != current_source:
                current_source = record.source.value
                current_section = None
                handle.write(f"## {record.source.title}\n\n")
                handle.write(f"- Source: {record.source.value}\n\n")

            section_key = (record.version, record.section_title)
            if section_key != current_section:
                current_section = section_key
                label = record.section_title or "Untitled section"
                if record.version:
                    label = f"{label} ({record.version})"
                handle.write(f"### {label}\n\n")

            handle.write(f"- L{record.line_no} **{record.speaker}**: {record.text}\n")


def write_dialogue_jsonl(path: Path, records: Iterable[DialogueRecord], append: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = "a" if append else "w"
    with path.open(mode, encoding="utf-8", newline="\n") as handle:
        for record in records:
            handle.write(json.dumps(record_to_dict(record), ensure_ascii=False) + "\n")


def record_to_dict(record: DialogueRecord) -> dict:
    return {
        "source": record.source.value,
        "source_title": record.source.title,
        "line_no": record.line_no,
        "speaker": record.speaker,
        "text": record.text,
        "section_title": record.section_title,
        "version": record.version,
    }


def now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).astimezone().isoformat(timespec="seconds")
