from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional, Sequence

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from story_parser.fetcher import read_text
    from story_parser.story_markdown import parse_story_markdown
else:
    from .story_parser.fetcher import read_text
    from .story_parser.story_markdown import parse_story_markdown


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "sources" / "extracted" / "story_preview.md"


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Parse mirrored BWiki story HTML into reviewable Markdown.")
    parser.add_argument("--html", action="append", type=Path, default=[], help="Local HTML file. Repeatable.")
    parser.add_argument("--manifest", type=Path, help="Mirror manifest generated by mirror_story_pages.py.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help=f"Markdown output. Default: {DEFAULT_OUTPUT}")
    parser.add_argument("--limit", type=int, default=0, help="Maximum pages to parse from manifest. 0 means no limit.")
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    html_paths = collect_html_paths(args)
    if not html_paths:
        print("No input. Use --html or --manifest.", file=sys.stderr)
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = [
        "# Story Markdown Preview",
        "",
        "> Generated by scripts/parse_story_markdown.py. Review before using as evidence.",
        "",
    ]

    for index, path in enumerate(html_paths, 1):
        print(f"[{index}/{len(html_paths)}] parsing {path}", file=sys.stderr)
        raw_html = read_text(path)
        result = parse_story_markdown(raw_html, display_path(path))
        parts.append(result.markdown)
        parts.append(
            f"<!-- parser_stats: title={result.title}; version={result.version}; "
            f"dialogue_count={result.dialogue_count}; choice_group_count={result.choice_group_count} -->"
        )
        parts.append("")

    args.output.write_text("\n".join(parts).strip() + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {args.output}", file=sys.stderr)
    return 0


def collect_html_paths(args: argparse.Namespace) -> list[Path]:
    paths = list(args.html)
    if args.manifest:
        manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
        output_dir = manifest_output_dir(manifest, args.manifest)
        for page in manifest.get("pages", []):
            local_path = page.get("local_path")
            if not local_path:
                continue
            paths.append(output_dir / local_path)
            if args.limit and len(paths) >= args.limit:
                break
    return paths


def display_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def manifest_output_dir(manifest: dict, manifest_path: Path) -> Path:
    value = manifest.get("output_dir")
    if not value:
        return manifest_path.parent
    path = Path(value)
    return path if path.is_absolute() else ROOT / path


if __name__ == "__main__":
    raise SystemExit(main())
